# Config File

adapters:
  ILLUMINACLIP:NexteraPE-PE.fa:2:30:10:8:true

bt2_genome:
  /home/groups/hoolock2/u0/genomes/ucsc/hg38/indexes/bowtie2/hg38

gtf:
  /home/groups/hoolock2/u0/genomes/ucsc/hg38/annotation/hg38.ncbiRefSeq.gtf

effective_genome_size:
  2913022398

treat_samples:
  ['H3K4me3', 'RUNX1']

control_sample:
  "control"

macs2_genome:
  hs

data_source:
  hg38

organism:
  Homo_sapiens
